# This is greedy player which reads/replays same inputs
# as generated by endgame_gen.

import argparse

import json
import noisy_mm
import random
import secrets

from greedy_player import posterior, sample_move
from pprint import pprint

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample", required=True)
    parser.add_argument("--temp", type=float, default=0.0)
    parser.add_argument("--p_corr", type=float, default=0.2, help="probability of each digit corruption")
    args = parser.parse_args()
    with open(args.sample, 'r') as file:
        sample = json.load(file)

    history = []
    for turn in sample['turns'][:-1]:
        [b, w] = turn['reply'].split()
        history.append((turn['guess'], int(b), int(w)))
    pprint(posterior(noisy_mm.DATASET, history, args.p_corr))


if __name__ == '__main__':
    main()
