# This is greedy player which reads/replays same inputs
# as generated by endgame_gen.

import argparse

import json
import noisy_mm
import random
import secrets

from greedy_player import posterior, sample_move
from pprint import pprint
from pathlib import Path

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--temp", type=float, default=0.0)
    parser.add_argument("--p_corr", type=float, default=0.2, help="probability of each digit corruption")
    args = parser.parse_args()
    files = sorted(Path("samples").glob("*.json"))
    dst = Path("samples_unique")
    for f in files:
        with open(f, 'r') as file:
            sample = json.load(file)

        history = []
        for turn in sample['turns'][:-1]:
            [b, w] = turn['reply'].split()
            history.append((turn['guess'], int(b), int(w)))
        
        belief = list(posterior(noisy_mm.DATASET, history, args.p_corr).items())
        probs = list(reversed(sorted([p for _, p in belief])))

        if len(probs) == 1 or probs[0] * 0.9 > probs[1]:
            sample["unique"] = True
            content_str = json.dumps(sample)
            with open(dst / f.name, "w") as fw:
                fw.write(content_str)


if __name__ == '__main__':
    main()
